version: '3'

services:
  dsa_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "dsa_backend"
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    container_name: "dsa_cn"
    restart: unless-stopped
